version: '3.5'

volumes:
  ms-sqlserver-data: {}

services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - '1433:1433'
    volumes:
      - ms-sqlserver-data:/var/opt/mssql
      - ./db:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh ${DB_USER} ${DB_PASSWORD} & /opt/mssql/bin/sqlservr;'

  api:
    build:
      context: ./server
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=1433
      - WAIT_HOSTS=db:1433
    ports:
      - '${API_PORT}:4000'
  web:
    build:
      context: client/
      args:
        REACT_APP_API_URL: 'http://localhost:${API_PORT}'
    ports:
      - '80:80'
